import AC1 from "./assets/ac1.png";
import CL1 from "./assets/cl1.png";
import CL2 from "./assets/cl2.png";
import AC3 from "./assets/ac3.png";
import E1 from "./assets/e1.png";
import AC5 from "./assets/ac5.png";
import AC6 from "./assets/ac6.png";
import E2 from "./assets/e2.png";
import CL7 from "./assets/cl7.png";

export const DataGuitar = [
  {
    id: 0,
    name: "Guitar Accoustic",
    title: "FENDER FSR V3 CD60",
    price: "4,900,000đ",
    desc: "CD-60 là một trong những mô hình phổ biến nhất của Fender và lý tưởng cho những người chơi đang tìm kiếm một cây đàn dáng dreadnought chất lượng cao giá cả phải",
    img: AC1,
    pro1: "+ Tặng 1 bộ dây savarez trị giá lên đến 400k",
    pro2: "+ Miễn phí vận chuyển",
    pro3: "+ Tặng bao đàn 3 lớp và capo khi mua sản phầm",
    pro4: "+ Tặng 1 giáo án về guitar và voucher giảm 50% khóa học về guitar",
  },
  {
    id: 1,
    name: "Guitar Classic",
    title: "CORDOBA 55FCE",
    price: "50,640,000đ",
    desc: "Thân đàn mỏng, chống feedback của 55FCE Negra được làm thủ công, làm cho cây đàn guitar sản xuất tại Tây Ban Nha này trở thành một công cụ thiết yếu trong kho vũ khí của các nhạc sĩ biểu diễn. Cây đàn được chọn của Gipsy Kings, mặt trên bằng gỗ vân sam châu Âu chắc chắn của nó được kết hợp với ziricote, mang lại âm thanh phong phú, mượt mà tràn ngập khắp căn phòng.",
    img: CL1,
    pro1: "+ Tặng 1 bộ dây savarez trị giá lên đến 400k",
    pro2: "+ Miễn phí vận chuyển",
    pro3: "+ Tặng bao đàn 3 lớp và capo khi mua sản phầm",
    pro4: "+ Tặng 1 giáo án về guitar và voucher giảm 50% khóa học về guitar",
  },
  {
    id: 2,
    name: "Guitar Classic",
    title: "TAKAMINE TC132SC TWCR",
    price: "33,960,000đ",
    desc: "Đàn Guitar Takamine TC132SC là một cây đàn cổ điển được chế tác hoàn toàn thủ công nên các chi tiết của đàn khá đẹp mắt và đạt được độ chuẩn về âm thanh",
    img: CL2,
    pro1: "+ Tặng 1 bộ dây savarez trị giá lên đến 400k",
    pro2: "+ Miễn phí vận chuyển",
    pro3: "+ Tặng bao đàn 3 lớp và capo khi mua sản phầm",
    pro4: "+ Tặng 1 giáo án về guitar và voucher giảm 50% khóa học về guitar",
  },
  {
    id: 3,
    name: "Guitar Accoutic",
    title: "TANGLEWOOD TWCR",
    price: "3,350,000đ",
    desc: "Đàn guitar acoustic Kiểu dáng Dreadnought Mặt trước : Mahogany tuyển chọn Mặt sau và bên hông: Mahogany  Cần đàn: Mahogany",
    img: AC3,
    pro1: "+ Tặng 1 bộ dây savarez trị giá lên đến 400k",
    pro2: "+ Miễn phí vận chuyển",
    pro3: "+ Tặng bao đàn 3 lớp và capo khi mua sản phầm",
    pro4: "+ Tặng 1 giáo án về guitar và voucher giảm 50% khóa học về guitar",
  },
  {
    id: 4,
    name: "Electronic Guitar",
    title: "FENDER SQUIER",
    price: "10,750,000đ",
    desc: "Là một con đường tuyệt vời để tiến đại vào gia đình Fender® lâu đời, Squier® Affinity Series ™ Stratocaster® QMT mang đến thiết kế huyền thoại và giai điệu tinh túy cho những Guitar Hero đầy khát vọng ngày na",
    img: E1,
    pro1: "+ Tặng 1 bộ dây savarez trị giá lên đến 400k",
    pro2: "+ Miễn phí vận chuyển",
    pro3: "+ Tặng bao đàn 3 lớp và capo khi mua sản phầm",
    pro4: "+ Tặng 1 giáo án về guitar và voucher giảm 50% khóa học về guitar",
  },
  {
    id: 5,
    name: "Guitar Accoutic",
    title: "FENDER CD-60S",
    price: "5,950,000đ",
    desc: "CD-60 là một trong những mô hình phổ biến nhất của Fender và lý tưởng cho những người chơi đang tìm kiếm một cây đàn dáng dreadnought chất lượng cao giá cả phải chăng",
    img: AC5,
    pro1: "+ Tặng 1 bộ dây savarez trị giá lên đến 400k",
    pro2: "+ Miễn phí vận chuyển",
    pro3: "+ Tặng bao đàn 3 lớp và capo khi mua sản phầm",
    pro4: "+ Tặng 1 giáo án về guitar và voucher giảm 50% khóa học về guitar",
  },
  {
    id: 6,
    name: "Guitar Accoutic",
    title: "TAYLOR AD17E",
    price: "42,000,000đ",
    desc: "Một cây dreadnought ngang vai dốc Grand Pacific AD17e được chế tạo từ gỗ tonewood rắn chắc (vân sam, ovangkol và mahogany).",
    img: AC6,
    pro1: "+ Tặng 1 bộ dây savarez trị giá lên đến 400k",
    pro2: "+ Miễn phí vận chuyển",
    pro3: "+ Tặng bao đàn 3 lớp và capo khi mua sản phầm",
    pro4: "+ Tặng 1 giáo án về guitar và voucher giảm 50% khóa học về guitar",
  },
  {
    id: 7,
    name: "Electronic Guitar",
    title: "FENDER SQUIER HSS",
    price: "9,320,000đ",
    desc: "Là một con đường tuyệt vời để tiến đại vào gia đình Fender® lâu đời, Squier® Affinity Series ™ Stratocaster® QMT mang đến thiết kế huyền thoại và giai điệu tinh túy cho những Guitarist",
    img: E2,
    pro1: "+ Tặng 1 bộ dây savarez trị giá lên đến 400k",
    pro2: "+ Miễn phí vận chuyển",
    pro3: "+ Tặng bao đàn 3 lớp và capo khi mua sản phầm",
    pro4: "+ Tặng 1 giáo án về guitar và voucher giảm 50% khóa học về guitar",
  },
  {
    id: 8,
    name: "Guitar Classic",
    title: "TAKAMINE TH90",
    price: "47,650,000đ",
    desc: "Takamine TH90 là cây đàn Classic được chế tác tinh tế với hệ thống Preamp Cool Tube CTP-3 mang đến âm thanh hoàn hảo cho người nghe Mặt trước    Solid Spruce",
    img: CL7,
    pro1: "+ Tặng 1 bộ dây savarez trị giá lên đến 400k",
    pro2: "+ Miễn phí vận chuyển",
    pro3: "+ Tặng bao đàn 3 lớp và capo khi mua sản phầm",
    pro4: "+ Tặng 1 giáo án về guitar và voucher giảm 50% khóa học về guitar",
  },
];
